### ISSUE TITLE
[Logger] What do you think about changing "winston" to "pino"

### ISSUE THREAD

**Issue by RunAge** [TheSoftwareHouse/node-common#35]
Pros:
 - Build in [Redaction / Obfuscation](https://getpino.io/#/docs/redaction?id=redaction)
 - [Log processing work on separate thread](https://getpino.io/#/?id=transports-amp-log-processing)
 - JSON logs with separate package to get nice readable ones [pino-pretty](https://github.com/pinojs/pino-pretty)
 - [Faster](https://github.com/pinojs/pino/blob/master/docs/benchmarks.md)
 
 
Cons:
 - Some work needed to create logs with similar style

**Comment by sethii** [comment]
So far we don't see logger performance to be an issue and so we don't really see the benefits. Just recently we've being doing some internal research about different loggers and at the end we decided to stay with winston, because there was no noticeable difference in performance and response time.
